export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout(props) {
  console.log("🚀 ~ RootLayout ~ props:", props);
  const { children } = props;

  return (
    <html lang="en">
      <body>
        <h1>children 表示子布局（如果有的话）或者子页面。</h1>
        {children}
      </body>
    </html>
  );
}
